/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ActivateSubscription": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AuroraBackofficeToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0ClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0ClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtRuntimeClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtRuntimeClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthCallback": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AuthLogin": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AuthLogout": {
      "name": string
      "type": "sst.aws.Function"
    }
    "BillingTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ChangePassword": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CreateAccessKey": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CreateBucket": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CreatePortalSession": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CreateSetupIntent": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DeleteAccessKey": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DeleteBucket": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DeleteMfaEnrollment": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DisableMfa": {
      "name": string
      "type": "sst.aws.Function"
    }
    "EnrollMfa": {
      "name": string
      "type": "sst.aws.Function"
    }
    "FthManagementApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GetActivity": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetBilling": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetBucket": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetBucketAnalytics": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetMe": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetUsage": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GracePeriodEnforcer": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GrafanaLokiAuth": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ListAccessKeys": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ListBuckets": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ListInvoices": {
      "name": string
      "type": "sst.aws.Function"
    }
    "OtelFirehoseBackup": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Presign": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RegenerateRecoveryCode": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ResendVerification": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SetupIntegrations": {
      "name": string
      "type": "sst.aws.Function"
    }
    "StripePriceId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripePublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhook": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SubscriptionDriftChecker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UpdateProfile": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UsageReportingOrchestrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UsageReportingWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UserFilesBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "UserInfoTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WebsiteBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "WebsiteRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}